const fusionList = [
{parents:[['rain','smoke'],['rain','smog']], children:['acid rain']},
{parents:[['bird','steel'],['bird','metal']], children:['airplane']},
{parents:[['clock','sound']], children:['alarm clock']},
{parents:[['fruit','time'],['juice','time']], children:['alcohol']},
{parents:[['water','plant'],['sea','plant'],['ocean','plant']], children:['algae']},
{parents:[['life','space']], children:['alien']},
{parents:[['human','dust']], children:['allergy']},
{parents:[['lizard','swamp'],['lizard','river']], children:['alligator']},
{parents:[['mountain','sheep']], children:['alpaca']},
{parents:[['car','hospital'],['car','doctor']], children:['ambulance']},
{parents:[['human','bird']], children:['angel']},
{parents:[['human','fishing rod']], children:['angler']},
{parents:[['grass','wild animal'],['wild animal','sugar']], children:['ant']},
{parents:[['snow','desert'],['ice','desert']], children:['antarctica']},
{parents:[['water','glass'],['glass','fish']], children:['aquarium']},
{parents:[['isle','isle']], children:['archipelago']},
{parents:[['wild animal','armor']], children:['armadillo']},
{parents:[['tool','metal'],['tool','steel']], children:['armor']},
{parents:[['volcano','energy']], children:['ash']},
{parents:[['human','moon'],['rocket','human'],['human','space station'],['human','space']], children:['astronaut']},
{parents:[['ice cream','astronaut']], children:['astronaut ice cream']},
{parents:[['air','pressure'],['sky','pressure']], children:['atmosphere']},
{parents:[['energy','explosion']], children:['atomic bomb']},
{parents:[['sun','antarctica'],['sky','antarctica'],['antarctica','atmosphere']], children:['aurora']},
{parents:[['energy','snow']], children:['avalanche']},
{parents:[['blade','wood']], children:['axe']},
{parents:[['pig','fire']], children:['bacon']},
{parents:[['swamp','life']], children:['bacteria']},
{parents:[['human','flour'],['human','bread'],['human','dough']], children:['baker']},
{parents:[['house','baker'],['house','bread']], children:['bakery']},
{parents:[['fruit','monkey']], children:['banana']},
{parents:[['bread','banana']], children:['banana bread']},
{parents:[['blood','fabric']], children:['bandage']},
{parents:[['house','money'],['house','gold'],['house','safe']], children:['bank']},
{parents:[['cow','house'],['livestock','house'],['house','hay']], children:['barn']},
{parents:[['mouse','bird'],['mouse','sky']], children:['bat']},
{parents:[['bat','human']], children:['batman']},
{parents:[['flour','milk']], children:['batter']},
{parents:[['gun','blade'],['gun','sword']], children:['bayonet']},
{parents:[['campfire','meat'],['campfire','garden']], children:['bbq']},
{parents:[['sea','sand'],['ocean','sand']], children:['beach']},
{parents:[['wild animal','wood'],['wild animal','dam']], children:['beaver']},
{parents:[['flower','wild animal']], children:['bee']},
{parents:[['bee','house'],['bee','tree']], children:['beehive']},
{parents:[['alcohol','wheat']], children:['beer']},
{parents:[['wheel','wheel']], children:['bicycle']},
{parents:[['air','life'],['life','sky'],['egg','air'],['egg','sky']], children:['bird']},
{parents:[['bird','house']], children:['birdhouse']},
{parents:[['star','pressure']], children:['black hole']},
{parents:[['metal','stone']], children:['blade']},
{parents:[['glass','blade'],['blade','electricity']], children:['blender']},
{parents:[['snow','snow'],['snow','storm'],['snow','wind']], children:['blizzard']},
{parents:[['human','blade']], children:['blood']},
{parents:[['engineer','paper']], children:['blueprint']},
{parents:[['water','wood']], children:['boat']},
{parents:[['steam','metal']], children:['boiler']},
{parents:[['corpse','time']], children:['bone']},
{parents:[['tree','pottery'],['tree','scissors']], children:['bonsai tree']},
{parents:[['paper','wood'],['paper','story']], children:['book']},
{parents:[['dough','fire']], children:['bread']},
{parents:[['clay','fire'],['mud','fire'],['mud','sun'],['clay','sun']], children:['brick']},
{parents:[['river','wood'],['river','metal'],['river','steel']], children:['bridge']},
{parents:[['wood','hay']], children:['broom']},
{parents:[['gunpowder','metal']], children:['bullet']},
{parents:[['bullet','armor']], children:['bulletproof vest']},
{parents:[['car','car']], children:['bus']},
{parents:[['human','meat']], children:['butcher']},
{parents:[['energy','milk'],['milk','pressure']], children:['butter']},
{parents:[['flower','wild animal']], children:['butterfly']},
{parents:[['desert','plant'],['sand','plant']], children:['cactus']},
{parents:[['dough','candle']], children:['cake']},
{parents:[['desert','wild animal'],['desert','horse'],['livestock','desert']], children:['camel']},
{parents:[['fire','wood']], children:['campfire']},
{parents:[['wax','thread'],['wax','fire']], children:['candle']},
{parents:[['sugar','christmas tree']], children:['candy cane']},
{parents:[['gunpowder','pirate ship'],['gunpowder','castle']], children:['cannon']},
{parents:[['hero','fabric']], children:['cape']},
{parents:[['wheel','metal']], children:['car']},
{parents:[['sugar','fire']], children:['caramel']},
{parents:[['human','oxygen'],['plant','night'],['tree','night']], children:['carbon dioxide']},
{parents:[['snowman','vegetable'],['sun','snowman']], children:['carrot']},
{parents:[['wheel','wood']], children:['cart']},
{parents:[['tool','mountain goat'],['thread','mountain goat'],['fabric','mountain goat'],['scissors','mountain goat'],['wool','mountain goat']], children:['cashmere']},
{parents:[['house','knight']], children:['castle']},
{parents:[['wild animal','milk']], children:['cat']},
{parents:[['cat','plant']], children:['catnip']},
{parents:[['metal','witch'],['steel','witch'],['fireplace','witch'],['campfire','witch']], children:['cauldron']},
{parents:[['hard roe','human']], children:['caviar']},
{parents:[['horse','human']], children:['centaur']},
{parents:[['wheat','milk']], children:['cereal']},
{parents:[['metal','rope'],['steel','rope']], children:['chain']},
{parents:[['axe','electricity']], children:['chainsaw']},
{parents:[['lizard','rainbow']], children:['chameleon']},
{parents:[['fire','wood']], children:['charcoal']},
{parents:[['time','milk']], children:['cheese']},
{parents:[['cheese','hamburger']], children:['cheeseburger']},
{parents:[['egg','livestock'],['livestock','bird'],['bird','farmer']], children:['chicken']},
{parents:[['water','chicken']], children:['chicken soup']},
{parents:[['chicken','bone']], children:['chicken wing']},
{parents:[['house','fireplace'],['smoke','brick'],['fireplace','brick']], children:['chimney']},
{parents:[['wool','fireplace']], children:['christmas stocking']},
{parents:[['light bulb','tree'],['tree','star']], children:['christmas tree']},
{parents:[['tobacco','paper']], children:['cigarette']},
{parents:[['village','village'],['skyscraper','skyscraper']], children:['city']},
{parents:[['sand','mud']], children:['clay']},
{parents:[['time','tool'],['time','wheel'],['time','electricity']], children:['clock']},
{parents:[['air','steam']], children:['cloud']},
{parents:[['pressure','plant'],['sun','snowman']], children:['coal']},
{parents:[['palm','fruit']], children:['coconut']},
{parents:[['coconut','tool'],['milk','coconut']], children:['coconut milk']},
{parents:[['wood','corpse']], children:['coffin']},
{parents:[['human','rain']], children:['cold']},
{parents:[['electricity','nerd'],['wire','nerd'],['tool','nerd']], children:['computer']},
{parents:[['mouse','computer']], children:['computer mouse']},
{parents:[['paper','blade'],['paper','scissors']], children:['confetti']},
{parents:[['book','recipe'],['recipe','recipe']], children:['cookbook']},
{parents:[['star','star']], children:['constellation']},
{parents:[['dough','sugar']], children:['cookie']},
{parents:[['human','gun'],['human','grim reaper']], children:['corpse']},
{parents:[['plant','cloud']], children:['cotton']},
{parents:[['grass','livestock']], children:['cow']},
{parents:[['rainbow','pencil'],['rainbow','wax']], children:['crayon']},
{parents:[['bird','scarecrow'],['bird','field']], children:['crow']},
{parents:[['gold','monarch'],['metal','monarch']], children:['crown']},
{parents:[['witch','glass'],['wizard','glass']], children:['crystal ball']},
{parents:[['clock','bird']], children:['cuckoo']},
{parents:[['human','robot']], children:['cyborg']},
{parents:[['bicycle','human']], children:['cyclist']},
{parents:[['beaver','river'],['beaver','tree'],['beaver','wood'],['wall','river']], children:['dam']},
{parents:[['jedi','fire'],['jedi','lava']], children:['darth vader']},
{parents:[['sun','time'],['night','sun'],['time','night'],['sky','sun']], children:['day']},
{parents:[['sand','sand'],['sand','cactus']], children:['desert']},
{parents:[['water','grass'],['fog','grass']], children:['dew']},
{parents:[['pressure','coal']], children:['diamond']},
{parents:[['lizard','time']], children:['dinosaur']},
{parents:[['human','hospital']], children:['doctor']},
{parents:[['wild animal','human']], children:['dog']},
{parents:[['dog','computer']], children:['doge']},
{parents:[['dog','house']], children:['doghouse']},
{parents:[['windmill','knight']], children:['don quixote']},
{parents:[['dough','oil']], children:['donut']},
{parents:[['rainbow','rainbow']], children:['double rainbow!']},
{parents:[['flour','water']], children:['dough']},
{parents:[['lizard','fire']], children:['dragon']},
{parents:[['airplane','robot']], children:['drone']},
{parents:[['wood','leather']], children:['drum']},
{parents:[['human','alcohol'],['beer','human'],['human','wine']], children:['drunk']},
{parents:[['carbon dioxide','cold'],['ice','carbon dioxide']], children:['dry ice']},
{parents:[['bird','lake'],['water','bird'],['bird','pond'],['time','duckling']], children:['duck']},
{parents:[['egg','duck']], children:['duckling']},
{parents:[['sand','wind'],['desert','wind'],['beach','wind']], children:['dune']},
{parents:[['earth','air'],['sun','vampire'],['day','vampire']], children:['dust']},
{parents:[['gunpowder','wire']], children:['dynamite']},
{parents:[['mountain','bird']], children:['eagle']},
{parents:[['earth','energy'],['earth','wave']], children:['earthquake']},
{parents:[['sun','moon']], children:['eclipse']},
{parents:[['life','stone'],['bird','bird'],['turtle','turtle'],['lizard','lizard']], children:['egg']},
{parents:[['egg','clock'],['egg','watch']], children:['egg timer']},
{parents:[['car','electricity']], children:['electric car']},
{parents:[['fish','electricity']], children:['electric eel']},
{parents:[['human','electricity'],['human','wire']], children:['electrician']},
{parents:[['metal','energy'],['solar cell','sun'],['wind turbine','wind'],['light','solar cell']], children:['electricity']},
{parents:[['letter','computer'],['letter','internet']], children:['email']},
{parents:[['air','fire'],['plant','sun']], children:['energy']},
{parents:[['human','tool']], children:['engineer']},
{parents:[['volcano','energy']], children:['eruption']},
{parents:[['sword','stone']], children:['excalibur']},
{parents:[['gunpowder','fire']], children:['explosion']},
{parents:[['thread','tool']], children:['fabric']},
{parents:[['story','monarch'],['story','castle'],['knight','story'],['dragon','story']], children:['fairy tale']},
{parents:[['human','house']], children:['family']},
{parents:[['tree','family']], children:['family tree']},
{parents:[['farmer','house'],['farmer','barn']], children:['farm']},
{parents:[['human','plant'],['field','human'],['human','pitchfork']], children:['farmer']},
{parents:[['goat','human']], children:['faun']},
{parents:[['wall','wood']], children:['fence']},
{parents:[['earth','farmer'],['earth','tool']], children:['field']},
{parents:[['fire','carbon dioxide'],['pressure','carbon dioxide'],['metal','carbon dioxide']], children:['fire extinguisher']},
{parents:[['human','fire'],['human','firetruck']], children:['fireman']},
{parents:[['house','campfire'],['campfire','brick'],['campfire','wall']], children:['fireplace']},
{parents:[['fireman','car']], children:['firetruck']},
{parents:[['explosion','sky']], children:['fireworks']},
{parents:[['hard roe','time']], children:['fish']},
{parents:[['fish','french fries']], children:['fish and chips']},
{parents:[['tool','fish'],['wood','fish']], children:['fishing rod']},
{parents:[['fire','gun']], children:['flamethrower']},
{parents:[['tool','light']], children:['flashlight']},
{parents:[['rain','rain'],['rain','time']], children:['flood']},
{parents:[['wheat','stone'],['windmill','wheat']], children:['flour']},
{parents:[['plant','garden']], children:['flower']},
{parents:[['wood','wind']], children:['flute']},
{parents:[['fish','bird'],['sky','fish']], children:['flying fish']},
{parents:[['squirrel','bird'],['squirrel','wind'],['squirrel','airplane'],['sky','squirrel']], children:['flying squirrel']},
{parents:[['earth','cloud']], children:['fog']},
{parents:[['tree','tree']], children:['forest']},
{parents:[['paper','cookie']], children:['fortune cookie']},
{parents:[['dinosaur','time'],['dinosaur','earth'],['stone','dinosaur']], children:['fossil']},
{parents:[['statue','water']], children:['fountain']},
{parents:[['chicken','wild animal']], children:['fox']},
{parents:[['zombie','electricity'],['electricity','corpse']], children:['frankenstein']},
{parents:[['oil','vegetable']], children:['french fries']},
{parents:[['metal','cold'],['electricity','cold'],['metal','ice']], children:['fridge']},
{parents:[['wild animal','pond']], children:['frog']},
{parents:[['tree','farmer'],['sun','tree']], children:['fruit']},
{parents:[['fruit','tree']], children:['fruit tree']},
{parents:[['star','star']], children:['galaxy']},
{parents:[['plant','plant'],['flower','flower'],['plant','grass'],['house','grass']], children:['garden']},
{parents:[['human','garden']], children:['gardener']},
{parents:[['steam','earth']], children:['geyser']},
{parents:[['graveyard','night'],['castle','night']], children:['ghost']},
{parents:[['santa','christmas tree'],['santa','christmas stocking'],['santa','cookie'],['santa','chimney'],['santa','fireplace']], children:['gift']},
{parents:[['house','dough'],['house','gingerbread man']], children:['gingerbread house']},
{parents:[['life','dough']], children:['gingerbread man']},
{parents:[['ice','mountain']], children:['glacier']},
{parents:[['fire','sand'],['sand','electricity']], children:['glass']},
{parents:[['glass','metal'],['glass','glass']], children:['glasses']},
{parents:[['garden','statue']], children:['gnome']},
{parents:[['livestock','mountain']], children:['goat']},
{parents:[['dinosaur','city']], children:['godzilla']},
{parents:[['metal','sun'],['metal','rainbow']], children:['gold']},
{parents:[['clay','life']], children:['golem']},
{parents:[['lava','pressure']], children:['granite']},
{parents:[['plant','earth']], children:['grass']},
{parents:[['coffin','earth'],['corpse','earth']], children:['grave']},
{parents:[['grave','stone']], children:['gravestone']},
{parents:[['grave','grave'],['gravestone','gravestone']], children:['graveyard']},
{parents:[['plant','glass'],['window','window']], children:['greenhouse']},
{parents:[['explosion','metal']], children:['grenade']},
{parents:[['cheese','toast']], children:['grilled cheese']},
{parents:[['human','scythe'],['corpse','scythe']], children:['grim reaper']},
{parents:[['metal','bullet']], children:['gun']},
{parents:[['fire','dust']], children:['gunpowder']},
{parents:[['rain','ice'],['ice','storm'],['ice','cloud']], children:['hail']},
{parents:[['meat','smoke']], children:['ham']},
{parents:[['meat','bread']], children:['hamburger']},
{parents:[['metal','wood']], children:['hammer']},
{parents:[['wheel','mouse']], children:['hamster']},
{parents:[['egg','water'],['egg','sea'],['egg','ocean'],['egg','pond'],['fish','fish']], children:['hard roe']},
{parents:[['angel','music']], children:['harp']},
{parents:[['farmer','grass'],['grass','scythe'],['grass','sun']], children:['hay']},
{parents:[['hay','hay']], children:['hay bale']},
{parents:[['plant','fence'],['leaf','fence']], children:['hedge']},
{parents:[['blade','airplane'],['windmill','airplane']], children:['helicopter']},
{parents:[['plant','sickness'],['sickness','leaf']], children:['herb']},
{parents:[['knight','dragon']], children:['hero']},
{parents:[['horse','river'],['horse','water']], children:['hippo']},
{parents:[['bee','flower'],['bee','beehive']], children:['honey']},
{parents:[['sky','earth'],['sea','sky'],['ocean','sky']], children:['horizon']},
{parents:[['hay','livestock']], children:['horse']},
{parents:[['metal','horse']], children:['horseshoe']},
{parents:[['house','sickness'],['house','ambulance'],['house','doctor']], children:['hospital']},
{parents:[['sand','glass']], children:['hourglass']},
{parents:[['wall','wall']], children:['house']},
{parents:[['earth','life']], children:['human']},
{parents:[['bird','flower']], children:['hummingbird']},
{parents:[['wind','energy']], children:['hurricane']},
{parents:[['snow','dog'],['ice','dog']], children:['husky']},
{parents:[['water','cold']], children:['ice']},
{parents:[['sea','ice'],['ocean','ice'],['sea','antarctica'],['ocean','antarctica']], children:['iceberg']},
{parents:[['milk','ice']], children:['ice cream']},
{parents:[['car','ice cream']], children:['ice cream truck']},
{parents:[['ice','tea'],['cold','tea']], children:['iced tea']},
{parents:[['human','light bulb'],['light bulb','nerd']], children:['idea']},
{parents:[['house','ice'],['house','snow']], children:['igloo']},
{parents:[['computer','computer'],['computer','wire'],['computer','web']], children:['internet']},
{parents:[['ocean','volcano'],['volcano','sea']], children:['isle']},
{parents:[['plant','wall']], children:['ivy']},
{parents:[['pumpkin','fire'],['blade','pumpkin'],['pumpkin','candle']], children:['jack-o-lantern']},
{parents:[['juice','sugar']], children:['jam']},
{parents:[['lightsaber','human'],['knight','lightsaber']], children:['jedi']},
{parents:[['meat','sun'],['meat','salt']], children:['jerky']},
{parents:[['water','fruit'],['pressure','fruit']], children:['juice']},
{parents:[['cat','music']], children:['keyboard cat']},
{parents:[['wind','paper'],['sky','paper']], children:['kite']},
{parents:[['human','armor']], children:['knight']},
{parents:[['water','pond'],['river','dam']], children:['lake']},
{parents:[['metal','light bulb']], children:['lamp']},
{parents:[['cow','rope'],['horse','rope']], children:['lasso']},
{parents:[['earth','fire']], children:['lava']},
{parents:[['lava','lamp']], children:['lava lamp']},
{parents:[['grass','tool'],['electricity','scythe']], children:['lawn mower']},
{parents:[['tree','wind']], children:['leaf']},
{parents:[['cow','blade'],['pig','blade']], children:['leather']},
{parents:[['fruit','water']], children:['lemonade']},
{parents:[['paper','pencil']], children:['letter']},
{parents:[['house','book']], children:['library']},
{parents:[['swamp','energy'],['love','time']], children:['life']},
{parents:[['light bulb','electricity'],['electricity','flashlight']], children:['light']},
{parents:[['electricity','glass']], children:['light bulb']},
{parents:[['light','house'],['light','beach'],['light','ocean'],['light','sea']], children:['lighthouse']},
{parents:[['light','sword'],['energy','sword'],['electricity','sword']], children:['lightsaber']},
{parents:[['wild animal','cat']], children:['lion']},
{parents:[['farmer','life'],['wild animal','human'],['farmer','wild animal']], children:['livestock']},
{parents:[['egg','swamp']], children:['lizard']},
{parents:[['wood','house']], children:['log cabin']},
{parents:[['human','human']], children:['love']},
{parents:[['axe','human'],['human','chainsaw']], children:['lumberjack']},
{parents:[['cheese','pasta']], children:['mac and cheese']},
{parents:[['human','letter']], children:['mailman']},
{parents:[['cow','sea']], children:['manatee']},
{parents:[['paper','earth']], children:['map']},
{parents:[['rust','planet']], children:['mars']},
{parents:[['sugar','campfire']], children:['marshmallows']},
{parents:[['egg','oil']], children:['mayonnaise']},
{parents:[['cow','tool'],['livestock','butcher'],['cow','butcher'],['pig','butcher'],['pig','tool'],['blade','livestock']], children:['meat']},
{parents:[['human','snake']], children:['medusa']},
{parents:[['human','fish']], children:['mermaid']},
{parents:[['fire','stone']], children:['metal']},
{parents:[['meteoroid','atmosphere'],['sky','meteoroid']], children:['meteor']},
{parents:[['stone','space']], children:['meteoroid']},
{parents:[['glass','bacteria'],['bacteria','glasses']], children:['microscope']},
{parents:[['farmer','cow'],['cow','human']], children:['milk']},
{parents:[['milk','ice cream']], children:['milk shake']},
{parents:[['human','cow']], children:['minotaur']},
{parents:[['glass','metal']], children:['mirror']},
{parents:[['time','bread']], children:['mold']},
{parents:[['human','castle'],['excalibur','human'],['crown','human']], children:['monarch']},
{parents:[['paper','gold']], children:['money']},
{parents:[['tree','wild animal']], children:['monkey']},
{parents:[['sky','cheese'],['sky','stone']], children:['moon']},
{parents:[['plant','stone'],['algae','stone']], children:['moss']},
{parents:[['moon','butterfly'],['night','butterfly']], children:['moth']},
{parents:[['bicycle','energy'],['bicycle','steel']], children:['motorcycle']},
{parents:[['earthquake','earth']], children:['mountain']},
{parents:[['mountain','goat'],['goat','mountain range']], children:['mountain goat']},
{parents:[['mountain','mountain']], children:['mountain range']},
{parents:[['cheese','wild animal']], children:['mouse']},
{parents:[['wood','cheese'],['metal','cheese']], children:['mousetrap']},
{parents:[['water','earth']], children:['mud']},
{parents:[['corpse','pyramid']], children:['mummy']},
{parents:[['human','flute'],['human','sound']], children:['music']},
{parents:[['unicorn','ocean'],['unicorn','water'],['sea','unicorn']], children:['narwhal']},
{parents:[['metal','thread'],['metal','hay']], children:['needle']},
{parents:[['human','glasses']], children:['nerd']},
{parents:[['story','lake']], children:['nessie']},
{parents:[['bird','tree'],['bird','hay'],['egg','hay']], children:['nest']},
{parents:[['paper','paper']], children:['newspaper']},
{parents:[['moon','time'],['time','day'],['sky','moon']], children:['night']},
{parents:[['shuriken','human']], children:['ninja']},
{parents:[['turtle','ninja']], children:['ninja turtle']},
{parents:[['tree','squirrel'],['fruit','squirrel']], children:['nut']},
{parents:[['desert','water']], children:['oasis']},
{parents:[['lava','water']], children:['obsidian']},
{parents:[['sea','sea'],['water','sea']], children:['ocean']},
{parents:[['sunflower','pressure']], children:['oil']},
{parents:[['clay','oil'],['potter','oil'],['oil','rope'],['glass','oil'],['fire','oil']], children:['oil lamp']},
{parents:[['egg','fire']], children:['omelette']},
{parents:[['wire','light']], children:['optical fiber']},
{parents:[['fruit tree','fruit tree'],['field','fruit tree']], children:['orchard']},
{parents:[['bird','paper']], children:['origami']},
{parents:[['bird','earth'],['bird','sand']], children:['ostrich']},
{parents:[['night','bird'],['bird','wizard']], children:['owl']},
{parents:[['plant','sun'],['plant','carbon dioxide']], children:['oxygen']},
{parents:[['oxygen','oxygen'],['oxygen','electricity']], children:['ozone']},
{parents:[['water','rainbow'],['water','pencil']], children:['paint']},
{parents:[['isle','tree'],['tree','beach']], children:['palm']},
{parents:[['wood','pressure']], children:['paper']},
{parents:[['airplane','paper']], children:['paper airplane']},
{parents:[['pilot','fabric'],['pilot','umbrella']], children:['parachute']},
{parents:[['bird','pirate']], children:['parrot']},
{parents:[['flour','egg']], children:['pasta']},
{parents:[['bird','rainbow']], children:['peacock']},
{parents:[['bird','horse'],['sky','horse'],['bird','unicorn']], children:['pegasus']},
{parents:[['wood','coal'],['wood','charcoal']], children:['pencil']},
{parents:[['blade','pencil']], children:['pencil sharpener']},
{parents:[['ice','wild animal'],['ice','bird'],['bird','snow']], children:['penguin']},
{parents:[['doctor','mold']], children:['penicillin']},
{parents:[['water','rose'],['water','flower'],['steam','rose'],['steam','flower'],['alcohol','rose'],['alcohol','flower']], children:['perfume']},
{parents:[['fossil','time'],['fossil','pressure']], children:['petroleum']},
{parents:[['fire','bird']], children:['phoenix']},
{parents:[['grass','sandwich'],['beach','sandwich']], children:['picnic']},
{parents:[['dough','fruit']], children:['pie']},
{parents:[['livestock','mud']], children:['pig']},
{parents:[['bird','city'],['bird','letter'],['bird','statue']], children:['pigeon']},
{parents:[['pig','money'],['pottery','pig']], children:['piggy bank']},
{parents:[['cotton','fabric']], children:['pillow']},
{parents:[['airplane','human'],['seaplane','human']], children:['pilot']},
{parents:[['wood','life']], children:['pinocchio']},
{parents:[['tobacco','wood']], children:['pipe']},
{parents:[['fish','blood']], children:['piranha']},
{parents:[['sword','sailor'],['sailor','pirate ship']], children:['pirate']},
{parents:[['sailboat','pirate'],['boat','pirate']], children:['pirate ship']},
{parents:[['tool','hay']], children:['pitchfork']},
{parents:[['cheese','dough']], children:['pizza']},
{parents:[['earth','space']], children:['planet']},
{parents:[['water','life'],['sea','life']], children:['plankton']},
{parents:[['rain','earth']], children:['plant']},
{parents:[['beaver','duck']], children:['platypus']},
{parents:[['water','garden']], children:['pond']},
{parents:[['juice','ice']], children:['popsicle']},
{parents:[['fire','clay'],['clay','wheel'],['clay','tool']], children:['pottery']},
{parents:[['earth','earth'],['air','air']], children:['pressure']},
{parents:[['paper','computer']], children:['printer']},
{parents:[['glass','rainbow']], children:['prism']},
{parents:[['air','dinosaur'],['bird','dinosaur']], children:['pterodactyl']},
{parents:[['snowman','flamethrower'],['sun','ice'],['sun','snowman']], children:['puddle']},
{parents:[['vegetable','fire'],['vegetable','light']], children:['pumpkin']},
{parents:[['desert','stone'],['desert','grave']], children:['pyramid']},
{parents:[['sand','swamp']], children:['quicksand']},
{parents:[['wild animal','carrot']], children:['rabbit']},
{parents:[['water','air']], children:['rain']},
{parents:[['rain','sun'],['rain','light']], children:['rainbow']},
{parents:[['wild animal','pirate ship'],['sailboat','wild animal']], children:['rat']},
{parents:[['flour','paper'],['paper','baker']], children:['recipe']},
{parents:[['santa','wild animal'],['livestock','santa']], children:['reindeer']},
{parents:[['diamond','metal'],['diamond','gold']], children:['ring']},
{parents:[['mountain','water'],['rain','mountain']], children:['river']},
{parents:[['metal','life'],['steel','life'],['life','armor']], children:['robot']},
{parents:[['airplane','space']], children:['rocket']},
{parents:[['train','mountain'],['mountain','cart']], children:['roller coaster']},
{parents:[['robot','vacuum cleaner']], children:['roomba']},
{parents:[['thread','thread']], children:['rope']},
{parents:[['plant','love'],['flower','love']], children:['rose']},
{parents:[['time','castle'],['time','house']], children:['ruins']},
{parents:[['wood','pencil']], children:['ruler']},
{parents:[['air','metal'],['metal','oxygen'],['steel','oxygen'],['air','steel']], children:['rust']},
{parents:[['car','house']], children:['rv']},
{parents:[['horse','leather']], children:['saddle']},
{parents:[['metal','money'],['metal','gold'],['steel','money'],['steel','gold']], children:['safe']},
{parents:[['explosion','glasses'],['tool','glasses'],['engineer','glasses']], children:['safety glasses']},
{parents:[['boat','wind'],['boat','fabric']], children:['sailboat']},
{parents:[['human','boat'],['human','sailboat']], children:['sailor']},
{parents:[['sea','sun'],['ocean','sun'],['fire','sea'],['fire','ocean']], children:['salt']},
{parents:[['air','stone']], children:['sand']},
{parents:[['sand','castle']], children:['sand castle']},
{parents:[['sand','paper']], children:['sandpaper']},
{parents:[['stone','sand']], children:['sandstone']},
{parents:[['sand','energy'],['sand','storm'],['sand','hurricane']], children:['sandstorm']},
{parents:[['bread','ham'],['cheese','bread'],['bread','bacon']], children:['sandwich']},
{parents:[['human','christmas tree']], children:['santa']},
{parents:[['ring','planet']], children:['saturn']},
{parents:[['blade','doctor'],['blade','hospital']], children:['scalpel']},
{parents:[['human','hay']], children:['scarecrow']},
{parents:[['blade','blade']], children:['scissors']},
{parents:[['wild animal','sand'],['wild animal','dune']], children:['scorpion']},
{parents:[['blade','grass'],['blade','wheat']], children:['scythe']},
{parents:[['water','water']], children:['sea']},
{parents:[['bird','sea'],['bird','ocean'],['bird','beach']], children:['seagull']},
{parents:[['horse','sea'],['ocean','horse'],['fish','horse']], children:['seahorse']},
{parents:[['dog','sea']], children:['seal']},
{parents:[['airplane','water'],['airplane','ocean'],['airplane','sea']], children:['seaplane']},
{parents:[['sickness','sea'],['sickness','ocean'],['boat','sickness'],['steamboat','sickness'],['sailboat','sickness']], children:['seasickness']},
{parents:[['plant','sea'],['plant','ocean']], children:['seaweed']},
{parents:[['electricity','needle'],['robot','needle']], children:['sewing machine']},
{parents:[['ocean','wild animal'],['sea','wild animal'],['sea','blood'],['blood','ocean']], children:['shark']},
{parents:[['cloud','livestock']], children:['sheep']},
{parents:[['paper','music']], children:['sheet music']},
{parents:[['star','blade']], children:['shuriken']},
{parents:[['human','bacteria'],['human','sickness'],['human','rain']], children:['sickness']},
{parents:[['snowboard','wheel']], children:['skateboard']},
{parents:[['corpse','time'],['bone','bone']], children:['skeleton']},
{parents:[['glasses','snow']], children:['ski goggles']},
{parents:[['air','cloud']], children:['sky']},
{parents:[['house','sky']], children:['skyscraper']},
{parents:[['snow','cart'],['snow','wagon']], children:['sledge']},
{parents:[['wild animal'],['time']], children:['sloth']},
{parents:[['smoke','fog'],['fog','city']], children:['smog']},
{parents:[['fire','wood']], children:['smoke']},
{parents:[['campfire','fabric'],['smoke','fabric']], children:['smoke signal']},
{parents:[['fruit','blender']], children:['smoothie']},
{parents:[['wild animal','wire']], children:['snake']},
{parents:[['steam','cold']], children:['snow']},
{parents:[['snow','human']], children:['snowball']},
{parents:[['wood','snow'],['snow','surfer']], children:['snowboard']},
{parents:[['glass','snow'],['snow','crystal ball']], children:['snow globe']},
{parents:[['snow','human'],['snowball','snowball'],['snow','carrot'],['snowball','carrot']], children:['snowman']},
{parents:[['snow','motorcycle'],['snow','car']], children:['snowmobile']},
{parents:[['oil','ash']], children:['soap']},
{parents:[['air','soap'],['water','soap']], children:['soap bubble']},
{parents:[['water','carbon dioxide'],['juice','carbon dioxide']], children:['soda']},
{parents:[['sun','tool']], children:['solar cell']},
{parents:[['sun','planet']], children:['solar system']},
{parents:[['air','wave']], children:['sound']},
{parents:[['sky','star'],['sun','star'],['moon','star']], children:['space']},
{parents:[['airplane','astronaut']], children:['spaceship']},
{parents:[['space','house']], children:['space station']},
{parents:[['thread','pasta']], children:['spaghetti']},
{parents:[['human','lion']], children:['sphinx']},
{parents:[['wild animal','thread']], children:['spider']},
{parents:[['sugar','confetti']], children:['sprinkles']},
{parents:[['mouse','tree']], children:['squirrel']},
{parents:[['sky','night'],['night','telescope']], children:['star']},
{parents:[['fish','star'],['sea','star'],['ocean','star']], children:['starfish']},
{parents:[['stone','tool'],['human','medusa']], children:['statue']},
{parents:[['fire','cow'],['meat','bbq']], children:['steak']},
{parents:[['water','fire'],['water','energy']], children:['steam']},
{parents:[['steam engine','water'],['steam engine','boat']], children:['steamboat']},
{parents:[['boiler','tool'],['boiler','wheel']], children:['steam engine']},
{parents:[['metal','coal']], children:['steel']},
{parents:[['steel','wool'],['wire','wool']], children:['steel wool']},
{parents:[['tool','doctor']], children:['stethoscope']},
{parents:[['air','lava']], children:['stone']},
{parents:[['energy','cloud'],['cloud','electricity']], children:['storm']},
{parents:[['human','campfire']], children:['story']},
{parents:[['fruit','energy'],['juice','fire'],['juice','energy']], children:['sugar']},
{parents:[['fire','sky']], children:['sun']},
{parents:[['clock','sun']], children:['sundial']},
{parents:[['plant','sun'],['flower','sun']], children:['sunflower']},
{parents:[['sun','glasses'],['beach','glasses']], children:['sunglasses']},
{parents:[['explosion','star']], children:['super nova']},
{parents:[['human','wave']], children:['surfer']},
{parents:[['fish','seaweed'],['caviar','seaweed']], children:['sushi']},
{parents:[['mud','plant'],['mud','grass']], children:['swamp']},
{parents:[['wool','tool'],['human','wool']], children:['sweater']},
{parents:[['glasses','water']], children:['swim goggles']},
{parents:[['human','swim goggles']], children:['swimmer']},
{parents:[['blade','metal'],['blade','steel']], children:['sword']},
{parents:[['fish','sword']], children:['swordfish']},
{parents:[['car','armor'],['car','gun']], children:['tank']},
{parents:[['gun','electricity']], children:['taser']},
{parents:[['water','leaf']], children:['tea']},
{parents:[['glass','sky'],['glass','star'],['glass','space']], children:['telescope']},
{parents:[['wood','fabric'],['house','fabric']], children:['tent']},
{parents:[['volcano','ring']], children:['the one ring']},
{parents:[['cotton','tool'],['wheel','wool']], children:['thread']},
{parents:[['sea','moon'],['ocean','moon']], children:['tide']},
{parents:[['sand','glass']], children:['time']},
{parents:[['steamboat','iceberg']], children:['titanic']},
{parents:[['sandwich','fire'],['bread','fire']], children:['toast']},
{parents:[['plant','fire']], children:['tobacco']},
{parents:[['metal','human']], children:['tool']},
{parents:[['bird','rainbow']], children:['toucan']},
{parents:[['farmer','car'],['field','car']], children:['tractor']},
{parents:[['steam engine','steel'],['steam engine','metal'],['steam engine','wheel'],['steam engine','wagon']], children:['train']},
{parents:[['pirate','treasure map']], children:['treasure']},
{parents:[['pirate','map']], children:['treasure map']},
{parents:[['plant','time']], children:['tree']},
{parents:[['tree','house']], children:['treehouse']},
{parents:[['horse','wood']], children:['trojan horse']},
{parents:[['ocean','earthquake'],['sea','earthquake']], children:['tsunami']},
{parents:[['engineer','mountain']], children:['tunnel']},
{parents:[['egg','sand']], children:['turtle']},
{parents:[['day','night']], children:['twilight']},
{parents:[['meat','dinosaur']], children:['tyrannosaurus rex']},
{parents:[['rocket','alien'],['airplane','alien']], children:['ufo']},
{parents:[['tool','rain'],['rain','fabric']], children:['umbrella']},
{parents:[['rainbow','horse'],['rainbow','life'],['double rainbow!','horse'],['double rainbow!','life']], children:['unicorn']},
{parents:[['electricity','broom']], children:['vacuum cleaner']},
{parents:[['human','blood'],['human','vampire']], children:['vampire']},
{parents:[['plant','pottery'],['pottery','flower']], children:['vase']},
{parents:[['field','fruit']], children:['vegetable']},
{parents:[['house','house']], children:['village']},
{parents:[['time','wine'],['air','wine'],['wine','oxygen']], children:['vinegar']},
{parents:[['lava','earth'],['lava','mountain'],['fire','mountain']], children:['volcano']},
{parents:[['bird','corpse']], children:['vulture']},
{parents:[['cart','horse']], children:['wagon']},
{parents:[['brick','brick']], children:['wall']},
{parents:[['leather','money']], children:['wallet']},
{parents:[['wizard','wood']], children:['wand']},
{parents:[['sword','human']], children:['warrior']},
{parents:[['human','clock']], children:['watch']},
{parents:[['water','gun']], children:['water gun']},
{parents:[['flower','pond']], children:['water lilly']},
{parents:[['water','pipe']], children:['water pipe']},
{parents:[['mountain','river']], children:['waterfall']},
{parents:[['water','wheel'],['wheel','river']], children:['waterwheel']},
{parents:[['ocean','wind'],['sea','wind']], children:['wave']},
{parents:[['bee','beehive']], children:['wax']},
{parents:[['spider','thread']], children:['web']},
{parents:[['wolf','human'],['werewolf','human']], children:['werewolf']},
{parents:[['field','farmer'],['plant','farmer']], children:['wheat']},
{parents:[['tool','wood']], children:['wheel']},
{parents:[['forest','life']], children:['wild animal']},
{parents:[['pig','wild animal'],['pig','forest']], children:['wild boar']},
{parents:[['pressure','air'],['air','energy']], children:['wind']},
{parents:[['house','wind'],['wheel','wind']], children:['windmill']},
{parents:[['windmill','electricity']], children:['wind turbine']},
{parents:[['glass','house']], children:['window']},
{parents:[['fruit','alcohol']], children:['wine']},
{parents:[['electricity','metal']], children:['wire']},
{parents:[['human','broom'],['wizard','broom']], children:['witch']},
{parents:[['human','energy']], children:['wizard']},
{parents:[['dog','forest'],['wild animal','moon'],['wild animal','dog']], children:['wolf']},
{parents:[['tool','tree']], children:['wood']},
{parents:[['bird','wood']], children:['woodpecker']},
{parents:[['sheep','tool'],['scissors','sheep']], children:['wool']},
{parents:[['gift','paper']], children:['wrapping paper']},
{parents:[['light','bone'],['light','skeleton']], children:['x-ray']},
{parents:[['cow','mountain']], children:['yak']},
{parents:[['jedi','swamp']], children:['yoda']},
{parents:[['milk','bacteria']], children:['yogurt']},
{parents:[['corpse','life']], children:['zombie']}];