/**
 * This list is the master list of all elements 
 * in the game.
 */
const masterElementList = [

    
    {name:'Acid Rain', discovered:false, img:'pink'},
    {name:'Air', discovered:true, img:'pink'},
    {name:'Airplane', discovered:false, img:'pink'},
    {name:'Alarm Clock', discovered:false, img:'pink'},
    {name:'Alcohol', discovered:false, img:'pink'},
    {name:'Algae', discovered:false, img:'pink'},
    {name:'Alien', discovered:false, img:'pink'},
    {name:'Allergy', discovered:false, img:'pink'},
    {name:'Alligator', discovered:false, img:'pink'},
    {name:'Alpaca', discovered:false, img:'pink'},
    {name:'Ambulance', discovered:false, img:'pink'},
    {name:'Angel', discovered:false, img:'pink'},
    {name:'Angler', discovered:false, img:'pink'},
    {name:'Ant', discovered:false, img:'pink'},
    {name:'Antarctica', discovered:false, img:'pink'},
    {name:'Aquarium', discovered:false, img:'pink'},
    {name:'Archipelago', discovered:false, img:'pink'},
    {name:'Armadillo', discovered:false, img:'pink'},
    {name:'Armor', discovered:false, img:'pink'},
    {name:'Ash', discovered:false, img:'pink'},
    {name:'Astronaut', discovered:false, img:'pink'},
    {name:'Astronaut Ice Cream', discovered:false, img:'pink'},
    {name:'Atmosphere', discovered:false, img:'pink'},
    {name:'Atomic Bomb', discovered:false, img:'pink'},
    {name:'Aurora', discovered:false, img:'pink'},
    {name:'Avalanche', discovered:false, img:'pink'},
    {name:'Axe', discovered:false, img:'pink'},
    {name:'Bacon', discovered:false, img:'pink'},
    {name:'Bacteria', discovered:false, img:'pink'},
    {name:'Baker', discovered:false, img:'pink'},
    {name:'Bakery', discovered:false, img:'pink'},
    {name:'Banana', discovered:false, img:'pink'},
    {name:'banana bread', discovered:false, img:'pink'},
    {name:'Bandage', discovered:false, img:'pink'},
    {name:'Bank', discovered:false, img:'pink'},
    {name:'Barn', discovered:false, img:'pink'},
    {name:'Bat', discovered:false, img:'pink'},
    {name:'Batman', discovered:false, img:'pink'},
    {name:'Batter', discovered:false, img:'pink'},
    {name:'Bayonet', discovered:false, img:'pink'},
    {name:'BBQ', discovered:false, img:'pink'},
    {name:'Beach', discovered:false, img:'pink'},
    {name:'Beaver', discovered:false, img:'pink'},
    {name:'Bee', discovered:false, img:'pink'},
    {name:'Beehive', discovered:false, img:'pink'},
    {name:'Beer', discovered:false, img:'pink'},
    {name:'Bicycle', discovered:false, img:'pink'},
    {name:'Bird', discovered:false, img:'pink'},
    {name:'Birdhouse', discovered:false, img:'pink'},
    {name:'Black Hole', discovered:false, img:'pink'},
    {name:'Blade', discovered:false, img:'pink'},
    {name:'Blender', discovered:false, img:'pink'},
    {name:'Blizzard', discovered:false, img:'pink'},
    {name:'Blood', discovered:false, img:'pink'},
    {name:'Blueprint', discovered:false, img:'pink'},
    {name:'Boat', discovered:false, img:'pink'},
    {name:'Boiler', discovered:false, img:'pink'},
    {name:'Bone', discovered:false, img:'pink'},
    {name:'Bonsai Tree', discovered:false, img:'pink'},
    {name:'Book', discovered:false, img:'pink'},
    {name:'Bread', discovered:false, img:'pink'},
    {name:'Brick', discovered:false, img:'pink'},
    {name:'Bridge', discovered:false, img:'pink'},
    {name:'Broom', discovered:false, img:'pink'},
    {name:'Bullet', discovered:false, img:'pink'},
    {name:'Bulletproof Vest', discovered:false, img:'pink'},
    {name:'Bus', discovered:false, img:'pink'},
    {name:'Butcher', discovered:false, img:'pink'},
    {name:'Butter', discovered:false, img:'pink'},
    {name:'Butterfly', discovered:false, img:'pink'},
    {name:'Cactus', discovered:false, img:'pink'},
    {name:'Cake', discovered:false, img:'pink'},
    {name:'Camel', discovered:false, img:'pink'},
    {name:'Campfire', discovered:false, img:'pink'},
    {name:'Candle', discovered:false, img:'pink'},
    {name:'Candy Cane', discovered:false, img:'pink'},
    {name:'Cannon', discovered:false, img:'pink'},
    {name:'Cape', discovered:false, img:'pink'},
    {name:'Car', discovered:false, img:'pink'},
    {name:'Caramel', discovered:false, img:'pink'},
    {name:'Carbon Dioxide', discovered:false, img:'pink'},
    {name:'Carrot', discovered:false, img:'pink'},
    {name:'Cart', discovered:false, img:'pink'},
    {name:'Cashmere', discovered:false, img:'pink'},
    {name:'Castle', discovered:false, img:'pink'},
    {name:'Cat', discovered:false, img:'pink'},
    {name:'Catnip', discovered:false, img:'pink'},
    {name:'Cauldron', discovered:false, img:'pink'},
    {name:'Caviar', discovered:false, img:'pink'},
    {name:'Centaur', discovered:false, img:'pink'},
    {name:'Cereal', discovered:false, img:'pink'},
    {name:'Chain', discovered:false, img:'pink'},
    {name:'Chainsaw', discovered:false, img:'pink'},
    {name:'Chameleon', discovered:false, img:'pink'},
    {name:'Charcoal', discovered:false, img:'pink'},
    {name:'Cheese', discovered:false, img:'pink'},
    {name:'Cheeseburger', discovered:false, img:'pink'},
    {name:'Chicken', discovered:false, img:'pink'},
    {name:'Chicken Soup', discovered:false, img:'pink'},
    {name:'Chicken wing', discovered:false, img:'pink'},
    {name:'Chimney', discovered:false, img:'pink'},
    {name:'Christmas Stocking', discovered:false, img:'pink'},
    {name:'Christmas Tree', discovered:false, img:'pink'},
    {name:'Cigarette', discovered:false, img:'pink'},
    {name:'City', discovered:false, img:'pink'},
    {name:'Clay', discovered:false, img:'pink'},
    {name:'Clock', discovered:false, img:'pink'},
    {name:'Cloud', discovered:false, img:'pink'},
    {name:'Coal', discovered:false, img:'pink'},
    {name:'Coconut', discovered:false, img:'pink'},
    {name:'Coconut Milk', discovered:false, img:'pink'},
    {name:'Coffin', discovered:false, img:'pink'},
    {name:'Cold', discovered:false, img:'pink'},
    {name:'Computer', discovered:false, img:'pink'},
    {name:'Computer Mouse', discovered:false, img:'pink'},
    {name:'Confetti', discovered:false, img:'pink'},
    {name:'Cookbook', discovered:false, img:'pink'},
    {name:'Constellation', discovered:false, img:'pink'},
    {name:'Cookie', discovered:false, img:'pink'},
    {name:'Corpse', discovered:false, img:'pink'},
    {name:'Cotton', discovered:false, img:'pink'},
    {name:'Cow', discovered:false, img:'pink'},
    {name:'Crayon', discovered:false, img:'pink'},
    {name:'Crow', discovered:false, img:'pink'},
    {name:'Crown', discovered:false, img:'pink'},
    {name:'Crystal Ball', discovered:false, img:'pink'},
    {name:'Cuckoo', discovered:false, img:'pink'},
    {name:'Cyborg', discovered:false, img:'pink'},
    {name:'Cyclist', discovered:false, img:'pink'},
    {name:'Dam', discovered:false, img:'pink'},
    {name:'Darth Vader', discovered:false, img:'pink'},
    {name:'Day', discovered:false, img:'pink'},
    {name:'Desert', discovered:false, img:'pink'},
    {name:'Dew', discovered:false, img:'pink'},
    {name:'Diamond', discovered:false, img:'pink'},
    {name:'Dinosaur', discovered:false, img:'pink'},
    {name:'Doctor', discovered:false, img:'pink'},
    {name:'Dog', discovered:false, img:'pink'},
    {name:'Doge', discovered:false, img:'pink'},
    {name:'Doghouse', discovered:false, img:'pink'},
    {name:'Don Quixote', discovered:false, img:'pink'},
    {name:'Donut', discovered:false, img:'pink'},
    {name:'Double Rainbow!', discovered:false, img:'pink'},
    {name:'Dough', discovered:false, img:'pink'},
    {name:'Dragon', discovered:false, img:'pink'},
    {name:'Drone', discovered:false, img:'pink'},
    {name:'Drum', discovered:false, img:'pink'},
    {name:'Drunk', discovered:false, img:'pink'},
    {name:'Dry Ice', discovered:false, img:'pink'},
    {name:'Duck', discovered:false, img:'pink'},
    {name:'Duckling', discovered:false, img:'pink'},
    {name:'Dune', discovered:false, img:'pink'},
    {name:'Dust', discovered:false, img:'pink'},
    {name:'Dynamite', discovered:false, img:'pink'},
    {name:'Eagle', discovered:false, img:'pink'},
    {name:'Earth', discovered:true, img:'pink'},
    {name:'Earthquake', discovered:false, img:'pink'},
    {name:'Eclipse', discovered:false, img:'pink'},
    {name:'Egg', discovered:false, img:'pink'},
    {name:'Egg Timer', discovered:false, img:'pink'},
    {name:'Electric Car', discovered:false, img:'pink'},
    {name:'Electric Eel', discovered:false, img:'pink'},
    {name:'Electrician', discovered:false, img:'pink'},
    {name:'Electricity', discovered:false, img:'pink'},
    {name:'Email', discovered:false, img:'pink'},
    {name:'Energy', discovered:false, img:'pink'},
    {name:'Engineer', discovered:false, img:'pink'},
    {name:'Eruption', discovered:false, img:'pink'},
    {name:'Excalibur', discovered:false, img:'pink'},
    {name:'Explosion', discovered:false, img:'pink'},
    {name:'Fabric', discovered:false, img:'pink'},
    {name:'Fairy Tale', discovered:false, img:'pink'},
    {name:'Family', discovered:false, img:'pink'},
    {name:'Family tree', discovered:false, img:'pink'},
    {name:'Farm', discovered:false, img:'pink'},
    {name:'Farmer', discovered:false, img:'pink'},
    {name:'Faun', discovered:false, img:'pink'},
    {name:'Fence', discovered:false, img:'pink'},
    {name:'Field', discovered:false, img:'pink'},
    {name:'Fire', discovered:true, img:'pink'},
    {name:'Fire Extinguisher', discovered:false, img:'pink'},
    {name:'Fireman', discovered:false, img:'pink'},
    {name:'Fireplace', discovered:false, img:'pink'},
    {name:'Firetruck', discovered:false, img:'pink'},
    {name:'Fireworks', discovered:false, img:'pink'},
    {name:'Fish', discovered:false, img:'pink'},
    {name:'Fish and Chips', discovered:false, img:'pink'},
    {name:'Fishing Rod', discovered:false, img:'pink'},
    {name:'Flamethrower', discovered:false, img:'pink'},
    {name:'Flashlight', discovered:false, img:'pink'},
    {name:'Flood', discovered:false, img:'pink'},
    {name:'Flour', discovered:false, img:'pink'},
    {name:'Flower', discovered:false, img:'pink'},
    {name:'Flute', discovered:false, img:'pink'},
    {name:'Flying Fish', discovered:false, img:'pink'},
    {name:'Flying Squirrel', discovered:false, img:'pink'},
    {name:'Fog', discovered:false, img:'pink'},
    {name:'Forest', discovered:false, img:'pink'},
    {name:'Fortune Cookie', discovered:false, img:'pink'},
    {name:'Fossil', discovered:false, img:'pink'},
    {name:'Fountain', discovered:false, img:'pink'},
    {name:'Fox', discovered:false, img:'pink'},
    {name:'Frankenstein', discovered:false, img:'pink'},
    {name:'French fries', discovered:false, img:'pink'},
    {name:'Fridge', discovered:false, img:'pink'},
    {name:'Frog', discovered:false, img:'pink'},
    {name:'Fruit', discovered:false, img:'pink'},
    {name:'Fruit Tree', discovered:false, img:'pink'},
    {name:'Galaxy', discovered:false, img:'pink'},
    {name:'Garden', discovered:false, img:'pink'},
    {name:'Gardener', discovered:false, img:'pink'},
    {name:'Geyser', discovered:false, img:'pink'},
    {name:'Ghost', discovered:false, img:'pink'},
    {name:'Gift', discovered:false, img:'pink'},
    {name:'Gingerbread house', discovered:false, img:'pink'},
    {name:'Gingerbread man', discovered:false, img:'pink'},
    {name:'Glacier', discovered:false, img:'pink'},
    {name:'Glass', discovered:false, img:'pink'},
    {name:'Glasses', discovered:false, img:'pink'},
    {name:'Gnome', discovered:false, img:'pink'},
    {name:'Goat', discovered:false, img:'pink'},
    {name:'Godzilla', discovered:false, img:'pink'},
    {name:'Gold', discovered:false, img:'pink'},
    {name:'Golem', discovered:false, img:'pink'},
    {name:'Granite', discovered:false, img:'pink'},
    {name:'Grass', discovered:false, img:'pink'},
    {name:'Grave', discovered:false, img:'pink'},
    {name:'Gravestone', discovered:false, img:'pink'},
    {name:'Graveyard', discovered:false, img:'pink'},
    {name:'Greenhouse', discovered:false, img:'pink'},
    {name:'Grenade', discovered:false, img:'pink'},
    {name:'Grilled cheese', discovered:false, img:'pink'},
    {name:'Grim Reaper', discovered:false, img:'pink'},
    {name:'Gun', discovered:false, img:'pink'},
    {name:'Gunpowder', discovered:false, img:'pink'},
    {name:'Hail', discovered:false, img:'pink'},
    {name:'Ham', discovered:false, img:'pink'},
    {name:'Hamburger', discovered:false, img:'pink'},
    {name:'Hammer', discovered:false, img:'pink'},
    {name:'Hamster', discovered:false, img:'pink'},
    {name:'Hard Roe', discovered:false, img:'pink'},
    {name:'Harp', discovered:false, img:'pink'},
    {name:'Hay', discovered:false, img:'pink'},
    {name:'Hay bale', discovered:false, img:'pink'},
    {name:'Hedge', discovered:false, img:'pink'},
    {name:'Helicopter', discovered:false, img:'pink'},
    {name:'Herb', discovered:false, img:'pink'},
    {name:'Hero', discovered:false, img:'pink'},
    {name:'Hippo', discovered:false, img:'pink'},
    {name:'Honey', discovered:false, img:'pink'},
    {name:'Horizon', discovered:false, img:'pink'},
    {name:'Horse', discovered:false, img:'pink'},
    {name:'Horseshoe', discovered:false, img:'pink'},
    {name:'Hospital', discovered:false, img:'pink'},
    {name:'Hourglass', discovered:false, img:'pink'},
    {name:'House', discovered:false, img:'pink'},
    {name:'Human', discovered:false, img:'pink'},
    {name:'Hummingbird', discovered:false, img:'pink'},
    {name:'Hurricane', discovered:false, img:'pink'},
    {name:'Husky', discovered:false, img:'pink'},
    {name:'Ice', discovered:false, img:'pink'},
    {name:'Iceberg', discovered:false, img:'pink'},
    {name:'Ice Cream', discovered:false, img:'pink'},
    {name:'Ice cream truck', discovered:false, img:'pink'},
    {name:'Iced tea', discovered:false, img:'pink'},
    {name:'Idea', discovered:false, img:'pink'},
    {name:'Igloo', discovered:false, img:'pink'},
    {name:'Internet', discovered:false, img:'pink'},
    {name:'Isle', discovered:false, img:'pink'},
    {name:'Ivy', discovered:false, img:'pink'},
    {name:'Jack-O-Lantern', discovered:false, img:'pink'},
    {name:'Jam', discovered:false, img:'pink'},
    {name:'Jedi', discovered:false, img:'pink'},
    {name:'Jerky', discovered:false, img:'pink'},
    {name:'Juice', discovered:false, img:'pink'},
    {name:'Keyboard Cat', discovered:false, img:'pink'},
    {name:'Kite', discovered:false, img:'pink'},
    {name:'Knight', discovered:false, img:'pink'},
    {name:'Lake', discovered:false, img:'pink'},
    {name:'Lamp', discovered:false, img:'pink'},
    {name:'Lasso', discovered:false, img:'pink'},
    {name:'Lava', discovered:false, img:'pink'},
    {name:'Lava Lamp', discovered:false, img:'pink'},
    {name:'Lawn Mower', discovered:false, img:'pink'},
    {name:'Leaf', discovered:false, img:'pink'},
    {name:'Leather', discovered:false, img:'pink'},
    {name:'Lemonade', discovered:false, img:'pink'},
    {name:'Letter', discovered:false, img:'pink'},
    {name:'Library', discovered:false, img:'pink'},
    {name:'Life', discovered:false, img:'pink'},
    {name:'Light', discovered:false, img:'pink'},
    {name:'Light Bulb', discovered:false, img:'pink'},
    {name:'Lighthouse', discovered:false, img:'pink'},
    {name:'Lightsaber', discovered:false, img:'pink'},
    {name:'Lion', discovered:false, img:'pink'},
    {name:'Livestock', discovered:false, img:'pink'},
    {name:'Lizard', discovered:false, img:'pink'},
    {name:'Log cabin', discovered:false, img:'pink'},
    {name:'Love', discovered:false, img:'pink'},
    {name:'Lumberjack', discovered:false, img:'pink'},
    {name:'Mac and Cheese', discovered:false, img:'pink'},
    {name:'Mailman', discovered:false, img:'pink'},
    {name:'Manatee', discovered:false, img:'pink'},
    {name:'Map', discovered:false, img:'pink'},
    {name:'Mars', discovered:false, img:'pink'},
    {name:'Marshmallows', discovered:false, img:'pink'},
    {name:'Mayonnaise', discovered:false, img:'pink'},
    {name:'Meat', discovered:false, img:'pink'},
    {name:'Medusa', discovered:false, img:'pink'},
    {name:'Mermaid', discovered:false, img:'pink'},
    {name:'Metal', discovered:false, img:'pink'},
    {name:'Meteor', discovered:false, img:'pink'},
    {name:'Meteoroid', discovered:false, img:'pink'},
    {name:'Microscope', discovered:false, img:'pink'},
    {name:'Milk', discovered:false, img:'pink'},
    {name:'Milk Shake', discovered:false, img:'pink'},
    {name:'Minotaur', discovered:false, img:'pink'},
    {name:'Mirror', discovered:false, img:'pink'},
    {name:'Mold', discovered:false, img:'pink'},
    {name:'Monarch', discovered:false, img:'pink'},
    {name:'Money', discovered:false, img:'pink'},
    {name:'Monkey', discovered:false, img:'pink'},
    {name:'Moon', discovered:false, img:'pink'},
    {name:'Moss', discovered:false, img:'pink'},
    {name:'Moth', discovered:false, img:'pink'},
    {name:'Motorcycle', discovered:false, img:'pink'},
    {name:'Mountain', discovered:false, img:'pink'},
    {name:'Mountain Goat', discovered:false, img:'pink'},
    {name:'Mountain Range', discovered:false, img:'pink'},
    {name:'Mouse', discovered:false, img:'pink'},
    {name:'Mousetrap', discovered:false, img:'pink'},
    {name:'Mud', discovered:false, img:'pink'},
    {name:'Mummy', discovered:false, img:'pink'},
    {name:'Music', discovered:false, img:'pink'},
    {name:'Narwhal', discovered:false, img:'pink'},
    {name:'Needle', discovered:false, img:'pink'},
    {name:'Nerd', discovered:false, img:'pink'},
    {name:'Nessie', discovered:false, img:'pink'},
    {name:'Nest', discovered:false, img:'pink'},
    {name:'Newspaper', discovered:false, img:'pink'},
    {name:'Night', discovered:false, img:'pink'},
    {name:'Ninja', discovered:false, img:'pink'},
    {name:'Ninja Turtle', discovered:false, img:'pink'},
    {name:'Nut', discovered:false, img:'pink'},
    {name:'Oasis', discovered:false, img:'pink'},
    {name:'Obsidian', discovered:false, img:'pink'},
    {name:'Ocean', discovered:false, img:'pink'},
    {name:'Oil', discovered:false, img:'pink'},
    {name:'Oil Lamp', discovered:false, img:'pink'},
    {name:'Omelette', discovered:false, img:'pink'},
    {name:'Optical Fiber', discovered:false, img:'pink'},
    {name:'Orchard', discovered:false, img:'pink'},
    {name:'Origami', discovered:false, img:'pink'},
    {name:'Ostrich', discovered:false, img:'pink'},
    {name:'Owl', discovered:false, img:'pink'},
    {name:'Oxygen', discovered:false, img:'pink'},
    {name:'Ozone', discovered:false, img:'pink'},
    {name:'Paint', discovered:false, img:'pink'},
    {name:'Palm', discovered:false, img:'pink'},
    {name:'Paper', discovered:false, img:'pink'},
    {name:'Paper Airplane', discovered:false, img:'pink'},
    {name:'Parachute', discovered:false, img:'pink'},
    {name:'Parrot', discovered:false, img:'pink'},
    {name:'Pasta', discovered:false, img:'pink'},
    {name:'Peacock', discovered:false, img:'pink'},
    {name:'Pegasus', discovered:false, img:'pink'},
    {name:'Pencil', discovered:false, img:'pink'},
    {name:'Pencil Sharpener', discovered:false, img:'pink'},
    {name:'Penguin', discovered:false, img:'pink'},
    {name:'Penicillin', discovered:false, img:'pink'},
    {name:'Perfume', discovered:false, img:'pink'},
    {name:'Petroleum', discovered:false, img:'pink'},
    {name:'Phoenix', discovered:false, img:'pink'},
    {name:'Picnic', discovered:false, img:'pink'},
    {name:'Pie', discovered:false, img:'pink'},
    {name:'Pig', discovered:false, img:'pink'},
    {name:'Pigeon', discovered:false, img:'pink'},
    {name:'Piggy Bank', discovered:false, img:'pink'},
    {name:'Pillow', discovered:false, img:'pink'},
    {name:'Pilot', discovered:false, img:'pink'},
    {name:'Pinocchio', discovered:false, img:'pink'},
    {name:'Pipe', discovered:false, img:'pink'},
    {name:'Piranha', discovered:false, img:'pink'},
    {name:'Pirate', discovered:false, img:'pink'},
    {name:'Pirate Ship', discovered:false, img:'pink'},
    {name:'Pitchfork', discovered:false, img:'pink'},
    {name:'Pizza', discovered:false, img:'pink'},
    {name:'Planet', discovered:false, img:'pink'},
    {name:'Plankton', discovered:false, img:'pink'},
    {name:'Plant', discovered:false, img:'pink'},
    {name:'Platypus', discovered:false, img:'pink'},
    {name:'Pond', discovered:false, img:'pink'},
    {name:'Popsicle', discovered:false, img:'pink'},
    {name:'Pottery', discovered:false, img:'pink'},
    {name:'Pressure', discovered:false, img:'pink'},
    {name:'Printer', discovered:false, img:'pink'},
    {name:'Prism', discovered:false, img:'pink'},
    {name:'Pterodactyl', discovered:false, img:'pink'},
    {name:'Puddle', discovered:false, img:'pink'},
    {name:'Pumpkin', discovered:false, img:'pink'},
    {name:'Pyramid', discovered:false, img:'pink'},
    {name:'Quicksand', discovered:false, img:'pink'},
    {name:'Rabbit', discovered:false, img:'pink'},
    {name:'Rain', discovered:false, img:'pink'},
    {name:'Rainbow', discovered:false, img:'pink'},
    {name:'Rat', discovered:false, img:'pink'},
    {name:'Recipe', discovered:false, img:'pink'},
    {name:'Reindeer', discovered:false, img:'pink'},
    {name:'Ring', discovered:false, img:'pink'},
    {name:'River', discovered:false, img:'pink'},
    {name:'Robot', discovered:false, img:'pink'},
    {name:'Rocket', discovered:false, img:'pink'},
    {name:'Roller Coaster', discovered:false, img:'pink'},
    {name:'Roomba', discovered:false, img:'pink'},
    {name:'Rope', discovered:false, img:'pink'},
    {name:'Rose', discovered:false, img:'pink'},
    {name:'Ruins', discovered:false, img:'pink'},
    {name:'Ruler', discovered:false, img:'pink'},
    {name:'Rust', discovered:false, img:'pink'},
    {name:'RV', discovered:false, img:'pink'},
    {name:'Saddle', discovered:false, img:'pink'},
    {name:'Safe', discovered:false, img:'pink'},
    {name:'Safety Glasses', discovered:false, img:'pink'},
    {name:'Sailboat', discovered:false, img:'pink'},
    {name:'Sailor', discovered:false, img:'pink'},
    {name:'Salt', discovered:false, img:'pink'},
    {name:'Sand', discovered:false, img:'pink'},
    {name:'Sand Castle', discovered:false, img:'pink'},
    {name:'Sandpaper', discovered:false, img:'pink'},
    {name:'Sandstone', discovered:false, img:'pink'},
    {name:'Sandstorm', discovered:false, img:'pink'},
    {name:'Sandwich', discovered:false, img:'pink'},
    {name:'Santa', discovered:false, img:'pink'},
    {name:'Saturn', discovered:false, img:'pink'},
    {name:'Scalpel', discovered:false, img:'pink'},
    {name:'Scarecrow', discovered:false, img:'pink'},
    {name:'Scissors', discovered:false, img:'pink'},
    {name:'Scorpion', discovered:false, img:'pink'},
    {name:'Scythe', discovered:false, img:'pink'},
    {name:'Sea', discovered:false, img:'pink'},
    {name:'Seagull', discovered:false, img:'pink'},
    {name:'Seahorse', discovered:false, img:'pink'},
    {name:'Seal', discovered:false, img:'pink'},
    {name:'Seaplane', discovered:false, img:'pink'},
    {name:'Seasickness', discovered:false, img:'pink'},
    {name:'Seaweed', discovered:false, img:'pink'},
    {name:'Sewing Machine', discovered:false, img:'pink'},
    {name:'Shark', discovered:false, img:'pink'},
    {name:'Sheep', discovered:false, img:'pink'},
    {name:'Sheet Music', discovered:false, img:'pink'},
    {name:'Shuriken', discovered:false, img:'pink'},
    {name:'Sickness', discovered:false, img:'pink'},
    {name:'Skateboard', discovered:false, img:'pink'},
    {name:'Skeleton', discovered:false, img:'pink'},
    {name:'Ski Goggles', discovered:false, img:'pink'},
    {name:'Sky', discovered:false, img:'pink'},
    {name:'Skyscraper', discovered:false, img:'pink'},
    {name:'Sledge', discovered:false, img:'pink'},
    {name:'Sloth', discovered:false, img:'pink'},
    {name:'Smog', discovered:false, img:'pink'},
    {name:'Smoke', discovered:false, img:'pink'},
    {name:'Smoke Signal', discovered:false, img:'pink'},
    {name:'Smoothie', discovered:false, img:'pink'},
    {name:'Snake', discovered:false, img:'pink'},
    {name:'Snow', discovered:false, img:'pink'},
    {name:'Snowball', discovered:false, img:'pink'},
    {name:'Snowboard', discovered:false, img:'pink'},
    {name:'Snow globe', discovered:false, img:'pink'},
    {name:'Snowman', discovered:false, img:'pink'},
    {name:'Snowmobile', discovered:false, img:'pink'},
    {name:'Soap', discovered:false, img:'pink'},
    {name:'Soap Bubble', discovered:false, img:'pink'},
    {name:'Soda', discovered:false, img:'pink'},
    {name:'Solar Cell', discovered:false, img:'pink'},
    {name:'Solar System', discovered:false, img:'pink'},
    {name:'Sound', discovered:false, img:'pink'},
    {name:'Space', discovered:false, img:'pink'},
    {name:'Spaceship', discovered:false, img:'pink'},
    {name:'Space Station', discovered:false, img:'pink'},
    {name:'Spaghetti', discovered:false, img:'pink'},
    {name:'Sphinx', discovered:false, img:'pink'},
    {name:'Spider', discovered:false, img:'pink'},
    {name:'Sprinkles', discovered:false, img:'pink'},
    {name:'Squirrel', discovered:false, img:'pink'},
    {name:'Star', discovered:false, img:'pink'},
    {name:'Starfish', discovered:false, img:'pink'},
    {name:'Statue', discovered:false, img:'pink'},
    {name:'Steak', discovered:false, img:'pink'},
    {name:'Steam', discovered:false, img:'pink'},
    {name:'Steamboat', discovered:false, img:'pink'},
    {name:'Steam Engine', discovered:false, img:'pink'},
    {name:'Steel', discovered:false, img:'pink'},
    {name:'Steel Wool', discovered:false, img:'pink'},
    {name:'Stethoscope', discovered:false, img:'pink'},
    {name:'Stone', discovered:false, img:'pink'},
    {name:'Storm', discovered:false, img:'pink'},
    {name:'Story', discovered:false, img:'pink'},
    {name:'Sugar', discovered:false, img:'pink'},
    {name:'Sun', discovered:false, img:'pink'},
    {name:'Sundial', discovered:false, img:'pink'},
    {name:'Sunflower', discovered:false, img:'pink'},
    {name:'Sunglasses', discovered:false, img:'pink'},
    {name:'Super nova', discovered:false, img:'pink'},
    {name:'Surfer', discovered:false, img:'pink'},
    {name:'Sushi', discovered:false, img:'pink'},
    {name:'Swamp', discovered:false, img:'pink'},
    {name:'Sweater', discovered:false, img:'pink'},
    {name:'Swim Goggles', discovered:false, img:'pink'},
    {name:'Swimmer', discovered:false, img:'pink'},
    {name:'Sword', discovered:false, img:'pink'},
    {name:'Swordfish', discovered:false, img:'pink'},
    {name:'Tank', discovered:false, img:'pink'},
    {name:'Taser', discovered:false, img:'pink'},
    {name:'Tea', discovered:false, img:'pink'},
    {name:'Telescope', discovered:false, img:'pink'},
    {name:'Tent', discovered:false, img:'pink'},
    {name:'The One Ring', discovered:false, img:'pink'},
    {name:'Thread', discovered:false, img:'pink'},
    {name:'Tide', discovered:false, img:'pink'},
    {name:'Time', discovered:false, img:'pink'},
    {name:'Titanic', discovered:false, img:'pink'},
    {name:'Toast', discovered:false, img:'pink'},
    {name:'Tobacco', discovered:false, img:'pink'},
    {name:'Tool', discovered:false, img:'pink'},
    {name:'Toucan', discovered:false, img:'pink'},
    {name:'Tractor', discovered:false, img:'pink'},
    {name:'Train', discovered:false, img:'pink'},
    {name:'Treasure', discovered:false, img:'pink'},
    {name:'Treasure map', discovered:false, img:'pink'},
    {name:'Tree', discovered:false, img:'pink'},
    {name:'Treehouse', discovered:false, img:'pink'},
    {name:'Trojan Horse', discovered:false, img:'pink'},
    {name:'Tsunami', discovered:false, img:'pink'},
    {name:'Tunnel', discovered:false, img:'pink'},
    {name:'Turtle', discovered:false, img:'pink'},
    {name:'Twilight', discovered:false, img:'pink'},
    {name:'Tyrannosaurus Rex', discovered:false, img:'pink'},
    {name:'UFO', discovered:false, img:'pink'},
    {name:'Umbrella', discovered:false, img:'pink'},
    {name:'Unicorn', discovered:false, img:'pink'},
    {name:'Vacuum Cleaner', discovered:false, img:'pink'},
    {name:'Vampire', discovered:false, img:'pink'},
    {name:'Vase', discovered:false, img:'pink'},
    {name:'Vegetable', discovered:false, img:'pink'},
    {name:'Village', discovered:false, img:'pink'},
    {name:'Vinegar', discovered:false, img:'pink'},
    {name:'Volcano', discovered:false, img:'pink'},
    {name:'Vulture', discovered:false, img:'pink'},
    {name:'Wagon', discovered:false, img:'pink'},
    {name:'Wall', discovered:false, img:'pink'},
    {name:'Wallet', discovered:false, img:'pink'},
    {name:'Wand', discovered:false, img:'pink'},
    {name:'Warrior', discovered:false, img:'pink'},
    {name:'Watch', discovered:false, img:'pink'},
    {name:'Water', discovered:true, img:'pink'},
    {name:'Water Gun', discovered:false, img:'pink'},
    {name:'Water Lilly', discovered:false, img:'pink'},
    {name:'Water Pipe', discovered:false, img:'pink'},
    {name:'Waterfall', discovered:false, img:'pink'},
    {name:'Waterwheel', discovered:false, img:'pink'},
    {name:'Wave', discovered:false, img:'pink'},
    {name:'Wax', discovered:false, img:'pink'},
    {name:'Web', discovered:false, img:'pink'},
    {name:'Werewolf', discovered:false, img:'pink'},
    {name:'Wheat', discovered:false, img:'pink'},
    {name:'Wheel', discovered:false, img:'pink'},
    {name:'Wild Animal', discovered:false, img:'pink'},
    {name:'Wild Boar', discovered:false, img:'pink'},
    {name:'Wind', discovered:false, img:'pink'},
    {name:'Windmill', discovered:false, img:'pink'},
    {name:'Wind Turbine', discovered:false, img:'pink'},
    {name:'Window', discovered:false, img:'pink'},
    {name:'Wine', discovered:false, img:'pink'},
    {name:'Wire', discovered:false, img:'pink'},
    {name:'Witch', discovered:false, img:'pink'},
    {name:'Wizard', discovered:false, img:'pink'},
    {name:'Wolf', discovered:false, img:'pink'},
    {name:'Wood', discovered:false, img:'pink'},
    {name:'Woodpecker', discovered:false, img:'pink'},
    {name:'Wool', discovered:false, img:'pink'},
    {name:'Wrapping Paper', discovered:false, img:'pink'},
    {name:'X-ray', discovered:false, img:'pink'},
    {name:'Yak', discovered:false, img:'pink'},
    {name:'Yoda', discovered:false, img:'pink'},
    {name:'Yogurt', discovered:false, img:'pink'},
    {name:'Zombie', discovered:false, img:'pink'}

];